### PR TITLE
Rebased onto kibae master

### PR DESCRIPTION
**Pull request by ltetzlaff**
- Add Typings
- Add Dockerfile to test support in `node-alpine` container
- Add Linting
- Bump to modern compiler flags for all platorms (not only osx)
- Pin package versions (especially `nan` should be fixed since we run node-gyp rebuild on package install)

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
actually, I don't like some part of the this patch.
for example 312b9bbf1, I don't understand why you change the formatting? it could occur every line changes.

**Comment by ltetzlaff** [comment]
> I don't understand why you change the formatting? it could occur every line changes.

Just found inconsistencies in the formatting, now that there's `prettier` in place it will all follow one consistent configurable style guideline ✌️

**Comment by d3m3vilurr** [comment]
why do you think `inconsistencies` at that time? most parts of the patch is `semicolon` and `quotation mark`. isn't it? :thinking: 
these conventions would be very personal tasty.
but I also follow it because it was pushed by project manager. ;)

**Comment by ltetzlaff** [comment]
Feel free to add something like this https://github.com/ltetzlaff/tslint-lt/blob/master/.prettierrc.yml and reference it in the `prettier` script in `package.json` if you miss semicolons or single quotes 😃
I wouldn't mind, just want it to be standardized 😇

**Comment by d3m3vilurr** [comment]
personally I prefer
```
printWidth: 80
tabWidth: 4 # but i know, many js projects have used softtab + tabstop 2.
useTabs: false
semi: true # I'm a python programmer too, so I like non-semi option. but sometimes js needs this case for clear meaning.
singleQuote: true # I don't like `double quote` because it needs `shift` combi. 
jsxSingleQuote: false # imo we don't need jsx options ;)
trailingComma: es5 # adding trailing comma gives small diff in the future.
bracketSpacing: false # idk why I don't like this. maybe I'm thinking that these spaces are useless.
jsxBracketSameLine: false
arrowParens: always
htmlWhitespaceSensitivity: css # same as jsx options
endOfLine: lf
```
it's quite different as default option ;)

**Pull request merged**
